import "@styles/globals.css";
import Nav from "@components/nav";

export const metadata = {
  title: "Xzect",
  description: "Generated by Subhadeep",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <main>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
